{{- $pullUrl := printf "http://$(%s):$(%s)/v1/pull" .Values.hostEnvVar .Values.portEnvVar -}}
{{- $pushUrl := printf "http://$(%s):$(%s)/v1/push" .Values.hostEnvVar .Values.authEnvVar -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.image.replicas }}
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.registrySecretName }}
      volumes:
        - name: sqlite-volume
          persistentVolumeClaim:
            claimName: simple-ebs
      containers:
        - name: casa-curator
          image: {{ .Values.image.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - mountPath: /app/db
            name: sqlite-volume
          command: ["casa-curator"]
          workingDir: /app
          args: ["continuous-populate-push", "--sleep-for",{{ .Values.sleepFor | quote }},"--sqlite-file",{{ .Values.sqliteFile | quote }},"--download-concurrency",{{ .Values.downloadConcurrency | quote }},"--push-url",{{ $pushUrl | quote }},"--pull-url",{{ $pullUrl | quote }}]
          resources:
{{ toYaml .Values.curatorResources.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
